name: Notify Slack Action
description: Send Github Actions workflow status notifications to Slack
author: RavSam Web Solutions
inputs:
  status:
    description: Job Status
    required: true
  notify_when:
    description: Specify on which events a slack notification is sent
    required: false
    default: 'success,failure,warnings'
  title:
    description: Slack notification title
    required: false
    default: CI notification triggered
  body:
    description: Slack notification body
    required: false
    default: The CI pipeline has failed

branding:
  icon: send
  color: blue

runs:
  using: docker
  image: Dockerfile
